# docker-compose.yml
#
# @author 김진규
# @since 2024.09.01
# @version 1.0
#
# <pre>
# 수정일        수정자        수정내용
# ----------  --------    ---------------------------
# 2024.09.01  김진규        최초 생성
# </pre>
# @since 2024.09.01
version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.5.10
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ALLOW_ANONYMOUS_LOGIN=yes
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka:2.12-2.2.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper
    container_name: kafka

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    container_name: redis

  nginx-rtmp:
    image: alfg/nginx-rtmp
    ports:
      - "1935:1935"
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx-rtmp

  themoonha-backend:
    build:
      context: .
    ports:
      - "8082:8080"
    depends_on:
      - kafka
      - nginx-rtmp
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      TNS_ADMIN: /app/config/wallet
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    volumes:
      - ${WALLET_PATH}:/app/config/wallet
    container_name: themoonha-backend