name: Deploy to Amazon EC2

on:
  push:
    branches:
      - develop #브랜치명

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
     - name:  기본 체크아웃
       uses: actions/checkout@v3
    
     - name: application.properties 설정
       run: |
          touch ./src/main/resources/application.properties
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties
          cat ./src/main/resources/application.properties

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    # S3 버킷에 업로드
     - name: Build project
       run: mvn clean package

     - name: Zip files for deployment
       run: |
          zip -r deployment.zip .

     - name: Upload to AWS S3
       run: |
          aws s3 cp deployment.zip s3://${{ secrets.S3_BUCKET }}/$GITHUB_SHA.zip

     - name: Deploy to EC2
       run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.AWS_CODE_DEPLOY_APPLICATION }} \
            --deployment-group-name ${{ secrets.AWS_CODE_DEPLOY_GROUP }} \
            --s3-location bucket=${{ secrets.S3_BUCKET }},key=$GITHUB_SHA.zip,bundleType=zip
